version: '1'

services:
  bera-frontend:
    image: bera-frontend
    container_name: bera-frontend
    build:
      context: ../bera-frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=production
    ports:
      - '9004:9004'
  mysql-docker-container:
    image: mysql
    container_name: mysql-docker-container
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_ROOT_PASSWORD=johnnypan
      - MYSQL_DATABASE=bera_prod_db
      - MYSQL_ROOT_HOST=%
    build:
      context: ./src/database/dump
      dockerfile: Dockerfile.db
    volumes:
      - database-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - shared-network
    restart: on-failure
  bera-backend:
    image: bera-backend
    container_name: bera-backend
    depends_on:
      - mysql-docker-container
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - '9001'
    ports:
      - '9001:9001'
    command: npm run start
    networks:
      - shared-network
    restart: on-failure

volumes:
  database-volume:

networks:
  shared-network: